config/routes.rb
Rails.application.routes.draw do
  get 'support/new'
  get 'support/create'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :dishes, only: [:destroy]
  resources :menus, only: [:show]
  get "menus/:id/qr_code", to: "menus#qr_show"
  resources :templates, only: [:index, :show]
  resources :support_requests, only: [:index]
  resources :users do
    resources :restaurants do
      resources :menus, only: [:index, :edit, :update, :destroy, :create, :new] do
        resources :dishes, except: [:destroy]
    end
  end
end
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
  belongs_to :template
  has_many :dishes
  accepts_nested_attributes_for :dishes
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: %i[show edit update destroy qr_show]
  skip_before_action :authenticate_user!, only: [:show]

  def index
    @menus = Menu.all
    @restaurants = current_user.restaurants
    @restaurant = Restaurant.find(params[:restaurant_id])
    @menus = policy_scope(Menu)
    @user = current_user
  end

  def show
    authorize @menu
    @user = current_user
    @restaurant = @menu.restaurant
    @dishes = Dish.all
    @starters = Dish.where("category = 'Starter'")
    @dinners = Dish.where("category = 'Dinner'")
    @lunches = Dish.where("category = 'Lunch'")
    @desserts = Dish.where("category = 'Dessert'")
    @sides = Dish.where("category = 'side'")
    @breakfasts = Dish.where("category = 'Breakfast'")
    @menus = policy_scope(Menu)
  end

  def new
    @menu = Menu.new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @user = current_user
    @templates = Template.all
    authorize @menu
  end

  def edit
    @qr_code = RQRCode::QRCode.new("http://www.melomenu.online/menus/#{@menu.id}")
    @svg = @qr_code.as_svg(
      module_size: 4
    )
    @user = current_user
    @restaurant = Restaurant.find(params[:restaurant_id])
    authorize @menu
    @starters = Dish.where("category = 'Starter'")
    @dinners = Dish.where("category = 'Dinner'")
    @lunches = Dish.where("category = 'Lunch'")
    @desserts = Dish.where("category = 'Dessert'")
    @sides = Dish.where("category = 'side'")
    @breakfasts = Dish.where("category = 'Breakfast'")
  end

  def create
    @menu = Menu.new(menu_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @menu.restaurant = @restaurant
    @menu.template = Template.find(params[:template_id])
    @templates = Template.all
    @user = current_user
    @dish = Dish.new
    if @menu.save
      @menu.qr_code = RQRCode::QRCode.new("http://www.melomenu.online/menus/#{@menu.id}")
      redirect_to new_user_restaurant_menu_dish_path(@user, @restaurant, @menu)
    else
      render :new, status: :unprocessable_entity
    end
    authorize @menu
  end

  def update
    @menu.update(menu_params)
    redirect_to menu_path(@menu)
    authorize @menu
  end

  def destroy
    @menu.destroy
    redirect_to restaurant_path(@menu.restaurant), status: :see_other
    authorize @menu
  end

  def qr_show
    authorize @menu
    @qr_code = RQRCode::QRCode.new("http://www.melomenu.online/menus/#{@menu.id}")
    @svg = @qr_code.as_svg
  end

  private

  def generate_qr_code
    @qr_code = RQRCode::QRCode.new(params[:qr_code].to_s)
  end

  def set_menu
    @menu = Menu.find(params[:id])
  end

  def menu_params
    params.require(:menu).permit(:menu_name, :id, :qr_code)
  end

end

app/views/menus/edit.html.erb
<div class="bg-container">

  <div class="container main-card h-full d-flex flex-column align-items-stretch card-content justify-content-start">


      <div class="d-flex justify-content-end w-full mt-20 mb-20">
      <p class="btn-primary-cards mx-10"><%= link_to "Add Dishes", new_user_restaurant_menu_dish_path(@user, @restaurant, @menu) %></p>
      <p class="btn-secondary-cards mx-10"><%= link_to "View Menu", menu_path(@menu) %></p>
      </div>

      <div class="w-full my-0" style="text-align:left">
        <h1 class ="my-0"><%= @menu.menu_name %></h1>
        <div class="edit-box">
          <div>
            <p class="pb-20"><strong> <%= @menu.restaurant.name %>: <%= @menu.restaurant.cuisine %></strong></p>
            <%= form_for @menu, url: user_restaurant_menu_path(@menu), method: :patch do |f| %>
              <div class="field">
                <%= f.label :name %>
                <%= f.text_field :menu_name %>
                <%= f.submit "Update", style: "font-size: 12px" %>
              </div>
            <% end %>
          </div>
          <a href=<%="/menus/#{@menu.id}/qr_code"%> >
          <%= @svg.html_safe %>
          </a>
        </div>
      </div>

        <div class="d-flex align-items-center justify-content-between"><h3 class="mt-20">Dishes on <%= @menu.menu_name %></h3>
        <p class="column-container">Jump to: <a href="#starters">Starters</a> | <a href="#breakfast">Breakfast</a> | <a href="#lunch">Lunch</a> | <a href="#dinner">Main Courses</a> | <a href="#sides">Sides</a> | <a href="#dessert">Dessert</a>
        </div>
      <div class="column-container d-flex flex-column">
        <h4 class="mb-0" id="starters">Starters</h4>
            <div class="dish-full">
              <div class="menu-text">
                <% @starters.each do |starter| %>
                  <% if starter.menu_id == @menu.id %>
                    <div class="d-flex align-items-center mt-20">
                      <p class="w-full d-flex align-items-center justify-content-start"><strong><%= starter.name %></strong>
                        <% if starter.dietary_type.include?("Vegan") %>
                          <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class= "diet-icon-column" >
                        <% end %>
                        <% if starter.dietary_type.include?("Vegetarian") %>
                          <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon-column" >
                        <% end %>
                        <% if starter.dietary_type.include?("Gluten-free") %>
                            <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon-column" >
                        <% end %>
                        <% if starter.dietary_type.include?("Lactose-free") %>
                            <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon-column" >
                        <% end %></p>

                      <p><strong>$<%= starter.price %></strong></p></div>
                      <p><%= starter.description%></p>

                <%= link_to " Edit Dish", edit_user_restaurant_menu_dish_path(@user, @restaurant, @menu, starter) %>
                <%= link_to " |  Delete Dish", dish_path(starter), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

                <% end %>
                <% end %>
                </div>
                </div>
                </div>

                <div class="column-container d-flex flex-column mt-20">
        <h4 class="mb-0 mt-20" id="breakfast">Breakfast</h4>
            <div class="dish-full">
              <div class="menu-text">
                <% @breakfasts.each do |breakfast| %>
                  <% if breakfast.menu_id == @menu.id %>
                    <div class="d-flex align-items-center mt-20">
                      <p class="w-full d-flex align-items-center justify-content-start"><strong><%= breakfast.name %></strong>
                        <% if breakfast.dietary_type.include?("Vegan") %>
                          <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class= "diet-icon-column" >
                        <% end %>
                        <% if breakfast.dietary_type.include?("Vegetarian") %>
                          <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon-column" >
                        <% end %>
                        <% if breakfast.dietary_type.include?("Gluten-free") %>
                            <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon-column" >
                        <% end %>
                        <% if breakfast.dietary_type.include?("Lactose-free") %>
                            <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon-column" >
                        <% end %></p>

                      <p><strong>$<%= breakfast.price %></strong></p></div>
                      <p><%= breakfast.description%></p>

                <%= link_to " Edit Dish", edit_user_restaurant_menu_dish_path(@user, @restaurant, @menu, breakfast) %>
                <%= link_to " |  Delete Dish", dish_path(breakfast), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

                <% end %>
                <% end %>
              </div>
              </div>
              </div>

               <div class="column-container d-flex flex-column mt-20">
                <h4 class="mb-0 mt-20" id="lunch">Lunch</h4>
                  <div class="dish-full">
                    <div class="menu-text">
                      <% @lunches.each do |lunch| %>
                      <% if lunch.menu_id == @menu.id %>
                        <div class="d-flex align-items-center mt-20">
                          <p class="w-full d-flex align-items-center justify-content-start"><strong><%= lunch.name %></strong>
                            <% if lunch.dietary_type.include?("Vegan") %>
                          <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class= "diet-icon-column" >
                            <% end %>
                            <% if lunch.dietary_type.include?("Vegetarian") %>
                          <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon-column" >
                            <% end %>
                            <% if lunch.dietary_type.include?("Gluten-free") %>
                            <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon-column" >
                            <% end %>
                            <% if lunch.dietary_type.include?("Lactose-free") %>
                            <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon-column" >
                            <% end %></p>

                              <p><strong>$<%= lunch.price %></strong></p></div>
                              <p><%= lunch.description%></p>

                <%= link_to " Edit Dish", edit_user_restaurant_menu_dish_path(@user, @restaurant, @menu, lunch) %>
                <%= link_to " |  Delete Dish", dish_path(lunch), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

                <% end %>
                <% end %>
              </div>
              </div>
              </div>

   <div class="column-container d-flex flex-column mt-20">
        <h4 class="mb-0 mt-20" id="dinner">Main Courses</h4>
            <div class="dish-full">
              <div class="menu-text">
                <% @dinners.each do |dinner| %>
                  <% if dinner.menu_id == @menu.id %>
                    <div class="d-flex align-items-center mt-20">
                      <p class="w-full d-flex align-items-center justify-content-start"><strong><%= dinner.name %></strong>
                        <% if dinner.dietary_type.include?("Vegan") %>
                          <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class= "diet-icon-column" >
                        <% end %>
                        <% if dinner.dietary_type.include?("Vegetarian") %>
                          <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon-column" >
                        <% end %>
                        <% if dinner.dietary_type.include?("Gluten-free") %>
                            <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon-column" >
                        <% end %>
                        <% if dinner.dietary_type.include?("Lactose-free") %>
                            <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon-column" >
                        <% end %></p>

                      <p><strong>$<%= dinner.price %></strong></p></div>
                      <p><%= dinner.description%></p>

                <%= link_to " Edit Dish", edit_user_restaurant_menu_dish_path(@user, @restaurant, @menu, dinner) %>
                <%= link_to " |  Delete Dish", dish_path(dinner), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

                <% end %>
                <% end %>
              </div>
              </div>
              </div>

   <div class="column-container d-flex flex-column mt-20">
        <h4 class="mb-0 mt-20" id="sides">Sides</h4>
            <div class="dish-full">
              <div class="menu-text">
                <% @sides.each do |side| %>
                  <% if side.menu_id == @menu.id %>
                    <div class="d-flex align-items-center mt-20">
                      <p class="w-full d-flex align-items-center justify-content-start"><strong><%= side.name %></strong>
                        <% if side.dietary_type.include?("Vegan") %>
                          <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class= "diet-icon-column" >
                        <% end %>
                        <% if side.dietary_type.include?("Vegetarian") %>
                          <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon-column" >
                        <% end %>
                        <% if side.dietary_type.include?("Gluten-free") %>
                            <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon-column" >
                        <% end %>
                        <% if side.dietary_type.include?("Lactose-free") %>
                            <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon-column" >
                        <% end %></p>

                      <p><strong>$<%= side.price %></strong></p></div>
                      <p><%= side.description%></p>

                <%= link_to " Edit Dish", edit_user_restaurant_menu_dish_path(@user, @restaurant, @menu, side) %>
                <%= link_to " |  Delete Dish", dish_path(side), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

                <% end %>
                <% end %>
              </div>
              </div>
              </div>

   <div class="column-container d-flex flex-column mt-20">
        <h4 class="mb-0 mt-20" id="dessert">Desserts</h4>
            <div class="dish-full">
              <div class="menu-text">
                <% @desserts.each do |dessert| %>
                  <% if dessert.menu_id == @menu.id %>
                    <div class="d-flex align-items-center mt-20">
                      <p class="w-full d-flex align-items-center justify-content-start"><strong><%= dessert.name %></strong>
                        <% if dessert.dietary_type.include?("Vegan") %>
                          <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class= "diet-icon-column" >
                        <% end %>
                        <% if dessert.dietary_type.include?("Vegetarian") %>
                          <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon-column" >
                        <% end %>
                        <% if dessert.dietary_type.include?("Gluten-free") %>
                            <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon-column" >
                        <% end %>
                        <% if dessert.dietary_type.include?("Lactose-free") %>
                            <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon-column" >
                        <% end %></p>

                      <p><strong>$<%= dessert.price %></strong></p></div>
                      <p><%= dessert.description%></p>

                <%= link_to " Edit Dish", edit_user_restaurant_menu_dish_path(@user, @restaurant, @menu, dessert) %>
                <%= link_to " |  Delete Dish", dish_path(dessert), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

                <% end %>
                <% end %>
              </div>
              </div>
              </div>
</div>












        </div>
      </div>

app/views/menus/index.html.erb
<div class=container>
  <h1>Menus</h1>
    <% @menus.each do | menu | %>
    <% if menu.restaurant_id = params[:restaurant_id]%>
      <ul>
        <li><%= menu.menu_name %>
          <%= link_to 'Edit this Menu', edit_user_restaurant_menu_path(@user, @restaurant, menu)%>
        </li>
      </ul>
    <% end %>
<% end %>
</div>

app/views/menus/new.html.erb
<body style="height: 100%">
<div class="bg-container-full">


  <div class="container main-card-wider d-flex flex-column align-items-stretch card-content">
  <h1>Create a New Menu</h1>

  <%= form_with model: @menu, url: user_restaurant_menus_path, method: :post do |form| %>
    <% if @menu.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>
        <ul>
          <% @menu.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
<div class="d-flex flex-column w-full">
      <div class="field d-flex align-items-center justify-items-center">
         <h4 class="mb-0 mr-10"><strong> <%= form.label :menu_name %>:</strong></h4>
          <p style="font-size: 14px"><%= form.text_field :menu_name %></p>
        </div>
        <br>
        <div class="field d-flex flex-column">
          <h4 class="mb-0 mt-0"><strong><%= form.label :template_id %> Choice:</strong></h4>
          <div class="d-flex w-full justify-content-between">
            <% @templates.each do |template| %>
              <div class="mr-4 mb-4 d-flex justify-content-start w-full align-items-center">
                <%= radio_button_tag(:template_id, template.id) %>
                <label class="pl-10"; style="font-size:16px"><%= template.name %></label>
              </div>
            <% end %>
          </div>
        </div>
        </div>
<br>
            <div class="actions d-flex">
              <%= form.submit 'Add Dishes', class: "btn-primary-cards mr-20" %>
              <div class="button">
      <%= link_to user_restaurants_path do%>
      <p class="btn-secondary-cards">Save Menu</p>
      <% end %>
      </div>

            </div>
<br>
      <% end %>

<div class="d-flex justify-content-between">

  <div class="template-container">
  <p class="template-img">Colourful</p>
    <div class="modal" id="modal-3" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-content-media w-900 h-800">
      <a href="#" class="close" role="button" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </a>
            <h5 class="modal-title text-white">Colourful Template</h5>
      <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678807223/Colourful_Menu_zyhxuv.png" class="img-fluid" alt="modal-img">
    </div>
  </div>
</div>
<!-- Page wrapper -->
<div class="page-wrapper">
  <!-- Modal toggle inside the content wrapper -->
  <div class="content-wrapper">
        <div data-toggle="modal" data-target="modal-3">
        <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678807223/Colourful_Menu_zyhxuv.png"; style="width: 150px">
      </div>
  </div>
</div>

  </div>


    <div class="template-container">
  <p class="template-img">Boho</p>
    <div class="modal" id="modal-4" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-content-media w-900 h-800">
      <a href="#" class="close" role="button" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </a>
            <h5 class="modal-title text-white">Boho Template</h5>
      <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678807223/Boho_Menu_apkotv.png" class="img-fluid" alt="modal-img">

    </div>
  </div>
</div>
<!-- Page wrapper -->
<div class="page-wrapper">
  <!-- Modal toggle inside the content wrapper -->
  <div class="content-wrapper">
        <div data-toggle="modal" data-target="modal-4">
        <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678807223/Boho_Menu_apkotv.png"; style="width: 150px">
      </div>
  </div>
</div>
  </div>


  <div class="template-container">
  <p class="template-img">Classic</p>
    <div class="modal" id="modal-6" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-content-media w-900 h-800">
      <a href="#" class="close" role="button" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </a>
            <h5 class="modal-title text-white">Classic Template</h5>
      <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678807225/Classic_Menu_w4lvjp.png" class="img-fluid" alt="modal-img">

    </div>
  </div>
</div>
<!-- Page wrapper -->
<div class="page-wrapper">
  <!-- Modal toggle inside the content wrapper -->
  <div class="content-wrapper">
        <div data-toggle="modal" data-target="modal-6">
        <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678807225/Classic_Menu_w4lvjp.png"; style="width: 150px">
      </div>
  </div>
</div>
  </div>


  <div class="template-container">
  <p class="template-img">Cute Cafe</p>
    <div class="modal" id="modal-5" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-content-media w-900 h-800">
      <a href="#" class="close" role="button" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </a>
            <h5 class="modal-title text-white">Cute Cafe Template</h5>
      <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678807231/Cafe_menu_wtb0lz.png" class="img-fluid" alt="modal-img">

    </div>
  </div>
</div>
<!-- Page wrapper -->
<div class="page-wrapper">
  <!-- Modal toggle inside the content wrapper -->
  <div class="content-wrapper">
        <div data-toggle="modal" data-target="modal-5">
        <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678807231/Cafe_menu_wtb0lz.png"; style="width: 150px">
      </div>
  </div>
</div>
  </div>

  <div class="template-container">
  <p class="template-img">Simple</p>
    <div class="modal" id="modal-7" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-content-media w-900 h-800">
      <a href="#" class="close" role="button" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </a>
            <h5 class="modal-title text-white">Simple Template</h5>
      <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678879933/Simple_Menu_tes6st.png" class="img-fluid" alt="modal-img">

    </div>
  </div>
</div>
<!-- Page wrapper -->
<div class="page-wrapper">
  <!-- Modal toggle inside the content wrapper -->
  <div class="content-wrapper">
        <div data-toggle="modal" data-target="modal-7">
        <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678879933/Simple_Menu_tes6st.png"; style="width: 150px">
      </div>
  </div>
</div>
  </div>




</div>
</div>

app/views/menus/qr_show.html.erb
<body style="height: 100vh">
<div class="bg-container">
<div class="main-card-short d-flex justify-content-center align-items-center">
<div class="container" id="container_qr">
  <%= @svg.html_safe %>
</div>
</div>
</div>

app/views/menus/show.html.erb
<% if @menu.template.name == "Colourful Template"%>
<%= render "shared/template1" %>
<% end %>

<% if @menu.template.name == "Boho Template"%>
<%= render "shared/template2" %>
<% end %>

<% if @menu.template.name == "Cute Cafe Template"%>
<%= render "shared/template3" %>
<% end %>

<% if @menu.template.name == "Classic Template"%>
<%= render "shared/template4" %>
<% end %>

<% if @menu.template.name == "Simple Template"%>
<%= render "shared/template5" %>
<% end %>