config/routes.rb
Rails.application.routes.draw do
  get 'support/new'
  get 'support/create'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :dishes, only: [:destroy]
  resources :menus, only: [:show]
  get "menus/:id/qr_code", to: "menus#qr_show"
  resources :templates, only: [:index, :show]
  resources :support_requests, only: [:index]
  resources :users do
    resources :restaurants do
      resources :menus, only: [:index, :edit, :update, :destroy, :create, :new] do
        resources :dishes, except: [:destroy]
    end
  end
end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-center">

  <div class="container p-4 pb-0">

      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-5" href="#!" role="button">
      <i class="fab fa-facebook-f"></i>
        </a>

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-5" href="#!" role="button">
      <i class="fab fa-twitter"></i>
        </a>

      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-5" href="#!" role="button">
      <i class="fab fa-google"></i>
        </a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-5" href="#!" role="button">
      <i class="fab fa-instagram"></i>
      </a>

  </div>

  <div class="text-center mt-10 pb-20">
    © by MeloMenu 2023
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="with-navbar">
<div class="navbar">
<div class="navbar-content container-fluid d-flex justify-content-between align-items-center">
    <%= link_to root_path, class: "navbar-brand" do %>
      <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678181935/Melo_logo_muj2f6.png">

<% if current_user.nil? %>
        <%= link_to 'sign in', new_user_session_path   %>
        <% else %>

<div class="dropdown">
  <button class="dropbtn" style="font-family: Bebas Neue;">Account</button>
  <div class="dropdown-content">

    <a href="<%= user_restaurants_path(user_id = current_user.id) %> ">My Menus</a>
    <a href="<%= support_requests_path %>">About Us</a>
    <%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete} %>
  </div>
</div>
<% end %>
<% end %>

    </div>
  </div>
  </div>

app/views/shared/_template1.html.erb
  <div class="template1-bg">
  <div class="template-header template-1">

      <div class="d-flex justify-content-center align-content-center">
        <div class="mx-20 my-20">
          <% if @menu.restaurant.user == current_user %>
          <p class="btn-primary-cards"><%= link_to "Add Dishes", new_user_restaurant_menu_dish_path(@user, @restaurant, @menu) %></p>
          <% end %>

        </div>

        <div class="mx-20 my-20">
          <% if @menu.restaurant.user == current_user %>
          <p class="btn-secondary-cards"><%= link_to 'Menu Dashboard', edit_user_restaurant_menu_path(@user, @restaurant, @menu)%></p>
          <% end %>

        </div>
      </div>

    <div class= "template-banner-1" >
    <div class="menu-name-1">
      <h1> <%= @menu.menu_name %> </h1>
    </div>
  </div>
  <div class="menu-main-card">
  <div class="icon-key-container-mobile align-items-center justify-content-end" style="background-color: lightgray;">
    <p class="icon-key"><img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class="diet-icon" > Vegan <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon"> Vegetarian <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon"> Gluten-Free <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon" %> Lactose-Free</p>
  </div>

<div class="container template-1">
  <div class="d-flex all-content-templates">
      <div class="d-flex px-40 flex-column menu-sidebar-1">

      <h3 class="text-light pt-20 ">Starters</h3>
                <div class="menu-text">
          <% @starters.each do |starter| %>
          <% if starter.menu_id == @menu.id %>
            <div class="d-flex justify-content-between">
              <p class="text-light"><strong class="d-flex align-items-center"><%= starter.name %>
                      <% if starter.dietary_type.include?("Vegan") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678387058/vegan-lt.png" class="diet-icon" >
              <% end %>
                 <% if starter.dietary_type.include?("Vegetarian") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678387057/veg-lt.png" class="diet-icon">
              <% end %>
                   <% if starter.dietary_type.include?("Gluten-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678387058/gf-lt.png" class="diet-icon">
              <% end %>
              <% if starter.dietary_type.include?("Lactose-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678387057/lf-lt.png" class="diet-icon">
              <% end %></p>
              <p class="text-light">$<%= starter.price %></strong></p>
            </div>
                  <p class="text-light mb-20 pb-20"><%= starter.description%></p>
         <% end %>
      <% end %>
    </div>
  </div>

    <div class="main-section">
  <div class="icon-key-container-full align-items-center justify-content-end" style="background-color: lightgray;">
    <p class="icon-key"><img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class="diet-icon" > Vegan <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon"> Vegetarian <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon"> Gluten-Free <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon" %> Lactose-Free</p>
    </div>

       <div class="d-flex flex-column menu-section justify-content-center ">
      <h3 class="text-dark pt-20 ">Breakfast</h3>
                <div class="menu-text w-full">

          <% @breakfasts.each do |breakfast| %>
          <% if breakfast.menu_id == @menu.id %>
                    <div class="d-flex justify-content-between">
              <p class="text-dark"><strong class="d-flex align-items-center"><%= breakfast.name %>
                      <% if breakfast.dietary_type.include?("Vegan") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class="diet-icon" >
              <% end %>
                 <% if breakfast.dietary_type.include?("Vegetarian") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon">
              <% end %>
                   <% if breakfast.dietary_type.include?("Gluten-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon">
              <% end %>
              <% if breakfast.dietary_type.include?("Lactose-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon" %>
              <% end %></p>
              <p>$<%= breakfast.price %></strong></p>
              </div>
                  <p><%= breakfast.description%></p>
         <% end %>
      <% end %>
  </div>
  </div>


      <div class="d-flex flex-column menu-section justify-content-center">
      <h3 class="text-dark pt-20 ">Lunch</h3>
                <div class="menu-text w-full">

          <% @lunches.each do |lunch| %>

          <% if lunch.menu_id == @menu.id %>
            <div class="d-flex justify-content-between">
              <p class="text-dark"><strong class="d-flex align-items-center"><%= lunch.name %>
                  <% if lunch.dietary_type.include?("Vegan") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class="diet-icon" >
              <% end %>

              <% if lunch.dietary_type.include?("Vegetarian") %>
                  <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon">
              <% end %>
                   <% if lunch.dietary_type.include?("Gluten-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon">

              <% end %>
              <% if lunch.dietary_type.include?("Lactose-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon" %>

              <% end %><p>
              <p>$<%= lunch.price %></p></strong>
              </div>
                <p><%= lunch.description%></p>
              <% end %>
      <% end %>
</div>
</div>

      <div class="d-flex flex-column menu-section justify-content-center ">
      <h3 class="text-dark pt-20 ">Dinner</h3>
        <div class="menu-text w-full">
          <% @dinners.each do |dinner| %>
          <% if dinner.menu_id == @menu.id %>
                    <div class="d-flex justify-content-between">
              <p class="text-dark"><strong class="d-flex align-items-center"><%= dinner.name %>
                      <% if dinner.dietary_type.include?("Vegan") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class="diet-icon" >
              <% end %>
                 <% if dinner.dietary_type.include?("Vegetarian") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon">
              <% end %>
                   <% if dinner.dietary_type.include?("Gluten-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon">

              <% end %>
              <% if dinner.dietary_type.include?("Lactose-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon" %>

              <% end %></p>
              <p>$<%= dinner.price %></strong></p>
              </div>
                  <p><%= dinner.description%></p>
         <% end %>
      <% end %>
  </div>
</div>
      <div class="d-flex flex-column menu-section justify-content-center ">
      <h3 class="text-dark pt-20 ">Sides</h3>
                <div class="menu-text w-full">
          <% @sides.each do |side| %>
          <% if side.menu_id == @menu.id %>
                    <div class="d-flex justify-content-between">
              <p class="text-dark"><strong class="d-flex align-items-center"><%= side.name %>
                      <% if side.dietary_type.include?("Vegan") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class="diet-icon" >
              <% end %>
                 <% if side.dietary_type.include?("Vegetarian") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon">
              <% end %>
                   <% if side.dietary_type.include?("Gluten-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon">

              <% end %>
              <% if side.dietary_type.include?("Lactose-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon" %>

              <% end %></p>
              <p>$<%= side.price %></strong></p>
              </div>
                  <p><%= side.description%></p>
         <% end %>
      <% end %>
  </div>
</div>
      <div class="d-flex flex-column menu-section justify-content-center ">
      <h3 class="text-dark pt-20 ">Desserts</h3>
                <div class="menu-text w-full">
          <% @desserts.each do |dessert| %>
          <% if dessert.menu_id == @menu.id %>
                    <div class="d-flex justify-content-between">
              <p class="text-dark"><strong class="d-flex align-items-center"><%= dessert.name %>
                      <% if dessert.dietary_type.include?("Vegan") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class="diet-icon" >
              <% end %>
                 <% if dessert.dietary_type.include?("Vegetarian") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon">
              <% end %>
                   <% if dessert.dietary_type.include?("Gluten-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon">

              <% end %>
              <% if dessert.dietary_type.include?("Lactose-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon" %>

              <% end %></p>
              <p>$<%= dessert.price %></strong></p>
              </div>
                  <p><%= dessert.description%></p>
         <% end %>
      <% end %>
  </div>

</div>
</div>
</div>
</div>
</div>

app/views/shared/_template2.html copy.erb
  <div class="template2-bg">
  <div class="template-header template-2">

      <div class="d-flex justify-content-center align-content-center">
        <div class="mx-20">
          <% if @menu.restaurant.user == current_user %>
          <p class="btn-primary"><%= link_to "Add Dishes", new_user_restaurant_menu_dish_path(@user, @restaurant, @menu) %></p>
          <% end %>

        </div>

        <div class="mx-20">
          <% if @menu.restaurant.user == current_user %>
          <p class="btn-secondary"><%= link_to 'Edit Menu', edit_user_restaurant_menu_path(@user, @restaurant, @menu)%></p>
          <% end %>

        </div>
      </div>

    <div class= "template-banner-2" >
    <div class="menu-name-2">
      <h1> <%= @menu.menu_name %> </h1>
    </div>
  </div>
  <div class="menu-main-card">
  <div class="icon-key-container-mobile align-items-center justify-content-end" style="background-color: lightgray;">
    <p class="icon-key"><img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class="diet-icon" > Vegan <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon"> Vegetarian <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon"> Gluten-Free <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon" %> Lactose-Free</p>
  </div>
<div class="container template-2">
  <div class="d-flex all-content">
      <div class="d-flex px-40 flex-column menu-sidebar-2">

      <h3 class="text-light pt-20 ">Starters</h3>
                <div class="menu-text">

          <% @starters.each do |starter| %>
          <% if starter.menu_id == @menu.id %>
            <div class="d-flex justify-content-between">
              <p class="text-light"><strong class="d-flex align-items-center"><%= starter.name %>
                      <% if starter.dietary_type.include?("Vegan") %>

                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678387058/vegan-lt.png" class="diet-icon" >
              <% end %>
                 <% if starter.dietary_type.include?("Vegetarian") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678387057/veg-lt.png" class="diet-icon">
              <% end %>
                   <% if starter.dietary_type.include?("Gluten-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678387058/gf-lt.png" class="diet-icon">
              <% end %>
              <% if starter.dietary_type.include?("Lactose-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678387057/lf-lt.png" class="diet-icon">
              <% end %></p>
              <p class="text-light">$<%= starter.price %></strong></p>
            </div>
                  <p class="text-light mb-20 pb-20"><%= starter.description%></p>
         <% end %>
      <% end %>
  </div>
  </div>

    <div class="main-section">
    <div class="icon-key-container-full align-items-center justify-content-end" style="background-color: lightgray;">
    <p class="icon-key"><img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class="diet-icon" > Vegan <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon"> Vegetarian <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon"> Gluten-Free <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon" %> Lactose-Free</p>
    </div>

       <div class="d-flex flex-column menu-section justify-content-center ">
      <h3 class="text-dark pt-20 ">Breakfast</h3>
                <div class="menu-text w-full">

          <% @breakfasts.each do |breakfast| %>
          <% if breakfast.menu_id == @menu.id %>
                    <div class="d-flex justify-content-between">
              <p class="text-dark"><strong class="d-flex align-items-center"><%= breakfast.name %>
                      <% if breakfast.dietary_type.include?("Vegan") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class="diet-icon" >
              <% end %>
                 <% if breakfast.dietary_type.include?("Vegetarian") %>
        <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon">

              <% end %>
                   <% if breakfast.dietary_type.include?("Gluten-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon">
              <% end %>
              <% if breakfast.dietary_type.include?("Lactose-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon" %>
              <% end %></p>
              <p>$<%= breakfast.price %></strong></p>
              </div>
                  <p><%= breakfast.description%></p>
         <% end %>
      <% end %>
  </div>
  </div>


      <div class="d-flex flex-column menu-section justify-content-center">
      <h3 class="text-dark pt-20 ">Lunch</h3>
                <div class="menu-text w-full">

          <% @lunches.each do |lunch| %>

          <% if lunch.menu_id == @menu.id %>
            <div class="d-flex justify-content-between">
              <p class="text-dark"><strong class="d-flex align-items-center"><%= lunch.name %>
                  <% if lunch.dietary_type.include?("Vegan") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class="diet-icon" >
              <% end %>

              <% if lunch.dietary_type.include?("Vegetarian") %>
         <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon">

              <% end %>
                   <% if lunch.dietary_type.include?("Gluten-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon">
              <% end %>
              <% if lunch.dietary_type.include?("Lactose-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon" %>
              <% end %><p>
              <p>$<%= lunch.price %></p></strong>
              </div>
                <p><%= lunch.description%></p>
              <% end %>
      <% end %>
</div>
</div>

      <div class="d-flex flex-column menu-section justify-content-center ">
      <h3 class="text-dark pt-20 ">Dinner</h3>
        <div class="menu-text w-full">
          <% @dinners.each do |dinner| %>
          <% if dinner.menu_id == @menu.id %>
                    <div class="d-flex justify-content-between">
              <p class="text-dark"><strong class="d-flex align-items-center"><%= dinner.name %>
                      <% if dinner.dietary_type.include?("Vegan") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class="diet-icon" >
              <% end %>
                 <% if dinner.dietary_type.include?("Vegetarian") %>
          <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon">

              <% end %>
                   <% if dinner.dietary_type.include?("Gluten-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon">
              <% end %>
              <% if dinner.dietary_type.include?("Lactose-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon" %>
              <% end %></p>
              <p>$<%= dinner.price %></strong></p>
              </div>
                  <p><%= dinner.description%></p>
         <% end %>
      <% end %>
  </div>
</div>
      <div class="d-flex flex-column menu-section justify-content-center ">
      <h3 class="text-dark pt-20 ">Sides</h3>
                <div class="menu-text w-full">
          <% @sides.each do |side| %>
          <% if side.menu_id == @menu.id %>
                    <div class="d-flex justify-content-between">
              <p class="text-dark"><strong class="d-flex align-items-center"><%= side.name %>
                      <% if side.dietary_type.include?("Vegan") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class="diet-icon" >
              <% end %>
                 <% if side.dietary_type.include?("Vegetarian") %>
    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon">

              <% end %>
                   <% if side.dietary_type.include?("Gluten-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon">
              <% end %>
              <% if side.dietary_type.include?("Lactose-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon" %>
              <% end %></p>
              <p>$<%= side.price %></strong></p>
              </div>
                  <p><%= side.description%></p>
         <% end %>
      <% end %>
  </div>
</div>
      <div class="d-flex flex-column menu-section justify-content-center ">
      <h3 class="text-dark pt-20 ">Desserts</h3>
                <div class="menu-text w-full">
          <% @desserts.each do |dessert| %>
          <% if dessert.menu_id == @menu.id %>
                    <div class="d-flex justify-content-between">
              <p class="text-dark"><strong class="d-flex align-items-center"><%= dessert.name %>
                      <% if dessert.dietary_type.include?("Vegan") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/vegan-dk.png" class="diet-icon" >
              <% end %>
                 <% if dessert.dietary_type.include?("Vegetarian") %>
            <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/veg-dk.png" class="diet-icon">

              <% end %>
                   <% if dessert.dietary_type.include?("Gluten-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/gf-dk.png" class="diet-icon">
              <% end %>
              <% if dessert.dietary_type.include?("Lactose-free") %>
                    <img src="https://res.cloudinary.com/dobohmdlf/image/upload/e_blackwhite/v1678387057/lf-dk.png" class="diet-icon" %>
              <% end %></p>
              <p>$<%= dessert.price %></strong></p>
              </div>
                  <p><%= dessert.description%></p>
         <% end %>
      <% end %>
  </div>

</div>
</div>
</div>
</div>
</div>