config/routes.rb
Rails.application.routes.draw do
  get 'support/new'
  get 'support/create'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :dishes, only: [:destroy]
  resources :menus, only: [:show]
  get "menus/:id/qr_code", to: "menus#qr_show"
  resources :templates, only: [:index, :show]
  resources :support_requests, only: [:index]
  resources :users do
    resources :restaurants do
      resources :menus, only: [:index, :edit, :update, :destroy, :create, :new] do
        resources :dishes, except: [:destroy]
    end
  end
end
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :menu
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

  before_action :set_dish, only: %i[show edit update destroy]

  def index
    @dishes = Dish.all
    @menu = Menu.find(params[:menu_id])
    @dish = Dish.new
    5.times { @menu.dishes.build }
    @dietary_types = ['Vegan', "Vegetarian", "Gluten-free", "Lactose-free"]
    authorize @dish
    @dishes = policy_scope(Dish)
  end

  def show
    authorize @dish
  end

  def new
    @menu = Menu.find(params[:menu_id])
    @dish = Dish.new
    @user = User.find(params[:user_id])
    @restaurant = Restaurant.find(params[:restaurant_id])
    5.times { @menu.dishes.build }
    # @dietary_types = ['Vegan', "Vegetarian", "Gluten-free", "Lactose-free"]
    authorize @dish
    @dishes = policy_scope(Dish)
    authorize @menu
    @user = current_user
    @restaurant = @menu.restaurant
    @dishes = Dish.all
    @starters = Dish.where("category = 'Starter'")
    @dinners = Dish.where("category = 'Dinner'")
    @lunches = Dish.where("category = 'Lunch'")
    @desserts = Dish.where("category = 'Dessert'")
    @sides = Dish.where("category = 'side'")
    @breakfasts = Dish.where("category = 'Breakfast'")
  end

  def edit
    authorize @dish
    @menu = Menu.find(params[:menu_id])
  end

  def create
    @dish = Dish.new(dish_params)
    @user = User.find(params[:user_id])
    @menu = Menu.find(params[:menu_id])
    @restaurant = Restaurant.find(params[:restaurant_id])
    @dish.menu = @menu
    if @dish.save
      redirect_to new_user_restaurant_menu_dish_path(@user, @restaurant, @menu), notice: "Created!"
    else
      render :new, status: :unprocessable_entity
    end
    authorize @dish
  end

  def update
    @dish.update(dish_params)
    @user = current_user
    @restaurant = Restaurant.find(params[:restaurant_id])
    @menu = Menu.find(params[:menu_id])
    redirect_to edit_user_restaurant_menu_path(@user, @restaurant, @menu), notice: "Successfully updated"
    authorize @dish
  end

  def destroy
    @dish.destroy
    @user = current_user
    @restaurant = Restaurant.find(params[:restaurant_id])
    @menu = Menu.find(params[:menu_id])
    redirect_to edit_user_restaurant_menu_path(@user, @restaurant, @menu), notice: "Successfully deleted"
    authorize @dish
  end

  private

  def set_dish
    @dish = Dish.find(params[:id])
  end

  def dish_params
    params.require(:dish).permit(:category, :name, :description, :dietary_type, :price)
  end

end

app/views/dishes/edit.html.erb
<body style="height: 100%">
<div class=bg-container-full>
<div class=main-card-index>

  <img class="corner-img" src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678881148/corner_image_menoet.png">
  <img class="sidebar-full" src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678891956/sidebar_cooking_lgruev.png">

  <div class="container p-20"; style="margin-bottom: 50px;">
  <h1 class="w-full all-content">Edit Dish</h1>

<%= form_for @dish, url: user_restaurant_menu_dish_path(@dish), method: :patch do |f| %>

  <p class="mb-10">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p class="mb-10">
    <%= f.label  :description %>
    <%= f.text_field :description %>
  </p>

  <p class="mb-10">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.submit "Update", class: "btn-primary-cards" %>
  </p>
<% end %>
</div>
</div>
</div>

app/views/dishes/index.html.erb
<div class="container">
  <h3>Dishes for <%= @menu.menu_name %> </h3>
    <% @dishes.each do | dish | %>
    <% if dish.menu_id == @menu.id %>
    <p><%= dish.name %></p>
    <% end %>
    <% end %>

</div>

app/views/dishes/new.html.erb
<body style="background-color:#edf7ff">
<div class="container my-20">
<h1>Add to <%= @menu.menu_name %> </h1>


<h3 class="ml-20 mb-0">Add to Starters </h3>

  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this menu from being saved:</h2>
      <ul>
        <% @dish.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-card d-flex align-items-start justify-content-around px-40">

<%= form_with model: @dish, url: user_restaurant_menu_dishes_path(@user, @restaurant, @menu), html: {class: "form-card"}, method: :post do |f| %>

    <%= f.text_field :category, value: "Starter", style: "display: none;"  %></p>
    <p><%= f.label :dish_name %>
    <%= f.text_field :name %></p>
    <p><%= f.label :description %>
    <%= f.text_field :description %></p>
    <p><%= f.label :dietary_type %>
    <%= f.select :dietary_type, ['Vegetarian', 'Vegan', 'Gluten-free', 'Lactose-free'], prompt: "Select one" %>
    <p><%= f.label :price %>
    <%= f.number_field :price, step: :any %></p>

  <%= f.submit "Add to Menu" %>
<% end %>


<div class="d-flex flex-column align-items-start justify-content-around">
  <h4>Dishes on <%= @menu.menu_name %> </h4>
    <% @starters.each do | starter | %>
    <% if starter.menu_id == @menu.id %>
    <p class="my-0"><%= starter.name %>........$<%= starter.price %>0</p>
    <% end %>
    <% end %>
</div>

</div>
</div>

</div>

<div class="container my-20">
<h3 class="ml-20 mb-0">Add to Main Courses</h3>


  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this menu from being saved:</h2>
      <ul>
        <% @dish.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-card d-flex align-items-start justify-content-around px-40">

<%= form_with model: @dish, url: user_restaurant_menu_dishes_path(@user, @restaurant, @menu), html: {class: "form-card"}, method: :post do |f| %>


    <%= f.text_field :category, value: "Dinner", style: "display: none;"  %></p>
    <p><%= f.label :dish_name %>
    <%= f.text_field :name %></p>
    <p><%= f.label :description %>
    <%= f.text_field :description %></p>
    <p><%= f.label :dietary_type %>
    <%= f.select :dietary_type, ['Vegetarian', 'Vegan', 'Gluten-free', 'Lactose-free'], prompt: "Select one" %>
    <p><%= f.label :price %>
    <%= f.number_field :price, step: :any %></p>


  <%= f.submit "Add to Menu" %>
<% end %>


<div class="d-flex flex-column align-items-start justify-content-around">
  <h4>Dishes on <%= @menu.menu_name %> </h4>
    <% @dinners.each do | dinner | %>
    <% if dinner.menu_id == @menu.id %>
    <p class="my-0"><%= dinner.name %>........$<%= dinner.price %>0</p>
    <% end %>
    <% end %>
</div>

</div>
</div>

</div>

<div class="container my-20">
<h3 class="ml-20 mb-0">Add to Side Dishes</h3>


  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this menu from being saved:</h2>
      <ul>
        <% @dish.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-card d-flex align-items-start justify-content-around px-40">

<%= form_with model: @dish, url: user_restaurant_menu_dishes_path(@user, @restaurant, @menu), html: {class: "form-card"}, method: :post do |f| %>

    <%= f.text_field :category, value: "side", style: "display: none;"  %></p>
    <p><%= f.label :dish_name %>
    <%= f.text_field :name %></p>
    <p><%= f.label :description %>
    <%= f.text_field :description %></p>
    <p><%= f.label :dietary_type %>
    <%= f.select :dietary_type, ['Vegetarian', 'Vegan', 'Gluten-free', 'Lactose-free'], prompt: "Select one" %>
    <p><%= f.label :price %>
    <%= f.number_field :price, step: :any %></p>


  <%= f.submit "Add to Menu" %>
<% end %>


<div class="d-flex flex-column align-items-start justify-content-around">
  <h4>Dishes on <%= @menu.menu_name %> </h4>
    <% @sides.each do | side | %>
    <% if side.menu_id == @menu.id %>
    <p class="my-0"><%= side.name %>........$<%= side.price %>0</p>
    <% end %>
    <% end %>
</div>

</div>
</div>

</div>


<div class="container my-20">
<h3 class="ml-20 mb-0">Add to Dessert </h3>


  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this menu from being saved:</h2>
      <ul>
        <% @dish.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-card d-flex align-items-start justify-content-around px-40">

<%= form_with model: @dish, url: user_restaurant_menu_dishes_path(@user, @restaurant, @menu), html: {class: "form-card"}, method: :post do |f| %>

    <%= f.text_field :category, value: "Dessert", style: "display: none;"  %></p>
    <p><%= f.label :dish_name %>
    <%= f.text_field :name %></p>
    <p><%= f.label :description %>
    <%= f.text_field :description %></p>
    <p><%= f.label :dietary_type %>
    <%= f.select :dietary_type, ['Vegetarian', 'Vegan', 'Gluten-free', 'Lactose-free'], prompt: "Select one" %>
    <p><%= f.label :price %>
    <%= f.number_field :price, step: :any %></p>


  <%= f.submit "Add to Menu" %>
<% end %>


<div class="d-flex flex-column align-items-start justify-content-around">
  <h4>Dishes on <%= @menu.menu_name %> </h4>
    <% @desserts.each do | dessert | %>
    <% if dessert.menu_id == @menu.id %>
    <p class="my-0"><%= dessert.name %>........$<%= dessert.price %>0</p>
    <% end %>
    <% end %>
</div>

</div>
</div>

</div>


<div class="container my-20">
<h3 class="ml-20 mb-0">Add to Breakfast</h3>


  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this menu from being saved:</h2>
      <ul>
        <% @dish.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-card d-flex align-items-start justify-content-around px-40">

<%= form_with model: @dish, url: user_restaurant_menu_dishes_path(@user, @restaurant, @menu), html: {class: "form-card"}, method: :post do |f| %>

    <%= f.text_field :category, value: "Breakfast", style: "display: none;"  %></p>
    <p><%= f.label :dish_name %>
    <%= f.text_field :name %></p>
    <p><%= f.label :description %>
    <%= f.text_field :description %></p>
    <p><%= f.label :dietary_type %>
    <%= f.select :dietary_type, ['Vegetarian', 'Vegan', 'Gluten-free', 'Lactose-free'], prompt: "Select one" %>
    <p><%= f.label :price %>
    <%= f.number_field :price, step: :any %></p>


  <%= f.submit "Add to Menu" %>
<% end %>


<div class="d-flex flex-column align-items-start justify-content-around">
  <h4>Dishes on <%= @menu.menu_name %> </h4>
    <% @breakfasts.each do | breakfast | %>
    <% if breakfast.menu_id == @menu.id %>
    <p class="my-0"><%= breakfast.name %>........$<%= breakfast.price %>0</p>
    <% end %>
    <% end %>
</div>

</div>
</div>

</div>


<div class="container my-20">
<h3 class="ml-20 mb-0">Add to Lunch</h3>


  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this menu from being saved:</h2>
      <ul>
        <% @dish.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-card d-flex align-items-start justify-content-around px-40">

<%= form_with model: @dish, url: user_restaurant_menu_dishes_path(@user, @restaurant, @menu), html: {class: "form-card"}, method: :post do |f| %>

    <%= f.text_field :category, value: "Lunch", style: "display: none;"  %></p>
    <p><%= f.label :dish_name %>
    <%= f.text_field :name %></p>
    <p><%= f.label :description %>
    <%= f.text_field :description %></p>
    <p><%= f.label :dietary_type %>
    <%= f.select :dietary_type, ['Vegetarian', 'Vegan', 'Gluten-free', 'Lactose-free'], prompt: "Select one" %>
    <p><%= f.label :price %>
    <%= f.number_field :price, step: :any %></p>


  <%= f.submit "Add to Menu" %>
<% end %>


<div class="d-flex flex-column align-items-start justify-content-around">
  <h4>Dishes on <%= @menu.menu_name %> </h4>
    <% @lunches.each do | lunch | %>
    <% if lunch.menu_id == @menu.id %>
    <p class="my-0"><%= lunch.name %>........$<%= lunch.price %>0</p>
    <% end %>
    <% end %>
</div>
</div>


</div>
<%= link_to 'Next', menu_path(@menu), class: "btn-secondary-cards sticky-button my-20 align-self-end" %>