config/routes.rb
Rails.application.routes.draw do
  get 'support/new'
  get 'support/create'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :dishes, only: [:destroy]
  resources :menus, only: [:show]
  get "menus/:id/qr_code", to: "menus#qr_show"
  resources :templates, only: [:index, :show]
  resources :support_requests, only: [:index]
  resources :users do
    resources :restaurants do
      resources :menus, only: [:index, :edit, :update, :destroy, :create, :new] do
        resources :dishes, except: [:destroy]
    end
  end
end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :menus
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    # @restaurants = current_user.restaurants
    @restaurants = policy_scope(Restaurant)
    @menus = Menu.all
    @user = User.find(params[:user_id])
    @images = ["https://res.cloudinary.com/dobohmdlf/image/upload/v1678647629/6574597-02_k56olg.png", "https://res.cloudinary.com/dobohmdlf/image/upload/v1678647628/6574597-01_gy5egh.png", "https://res.cloudinary.com/dobohmdlf/image/upload/v1678647628/6574597-03_pdijez.png", "https://res.cloudinary.com/dobohmdlf/image/upload/v1678734089/6574597-05_s7ozav.png", "https://res.cloudinary.com/dobohmdlf/image/upload/v1678734088/6574597-04_r6olc6.png" ]

  end

  def show
    authorize @restaurant
    @restaurant = Restaurant.find(params[:id])
    @user = User.find(params[:user_id])
    @restaurants = Restaurant.all
    @menus = Menu.all
    @images = ["https://res.cloudinary.com/dobohmdlf/image/upload/v1678647629/6574597-02_k56olg.png", "https://res.cloudinary.com/dobohmdlf/image/upload/v1678647628/6574597-01_gy5egh.png", "https://res.cloudinary.com/dobohmdlf/image/upload/v1678647628/6574597-03_pdijez.png", "https://res.cloudinary.com/dobohmdlf/image/upload/v1678734089/6574597-05_s7ozav.png", "https://res.cloudinary.com/dobohmdlf/image/upload/v1678734088/6574597-04_r6olc6.png" ]
  end

  def new

    @restaurant = current_user.restaurants.build
    authorize @restaurant
  end

  def create

    @restaurant = current_user.restaurants.build(restaurant_params)
    @user = current_user
    @menu = Menu.new()
    if @restaurant.save
      redirect_to new_user_restaurant_menu_path(@user, @restaurant, @menu), notice: 'Restaurant was successfully created.'
    else
      render :new
    end
    authorize @restaurant
  end

  def edit
    authorize @restaurant
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @user = current_user
    if @restaurant.update(restaurant_params)
      redirect_to user_restaurant_path(@user, @restaurant)
    else
      render 'edit'
    end
    authorize @restaurant
  end

  def destroy
    @restaurant = current_user.restaurants.find(params[:id])
    @restaurant.destroy
    redirect_to user_restaurants_path, notice: 'Restaurant was successfully deleted.'
    authorize @restaurant
  end

  private

  def set_restaurant
    @restaurant = current_user.restaurants.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :cuisine, :address, :phone_number, :website, :email)
  end
end

app/views/restaurants/edit.html.erb
<body style="height: 100%">

<div class="bg-container-full">
  <div class="container main-card-index d-flex flex-column align-items-stretch card-content">
  <img class="corner-img" src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678881148/corner_image_menoet.png">
  <img class="sidebar-full" src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678898291/sidebar_food2_jappzs.png">

    <div class="container p-20"; style="margin-bottom: 50px;">
      <h1 class="w-full all-content">Edit Restaurant</h1>

      <%= form_for @restaurant, url: user_restaurant_path(@restaurant), method: :patch do |f| %>

        <p class="mb-10">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </p>

        <p class="mb-10">
          <%= f.label  :cuisine %>
          <%= f.text_field :cuisine %>
        </p>

        <p class="mb-10">
          <%= f.label :address %>
          <%= f.text_field :address %>
        </p>

        <p class="mb-10">
          <%= f.label :phone_number %>
          <%= f.text_field :phone_number %>
        </p>

        <p class="mb-10">
          <%= f.label :website %>
          <%= f.text_field :website %>
        </p>

        <p class="mb-10">
          <%= f.label :email %>
          <%= f.text_field :email %>
        </p>

        <p>
          <%= f.submit "Update", class: "btn-primary-cards mr-20" %>
        </p>
      <% end %>
    </div>

  </div>
</div>
</div>

app/views/restaurants/index.html.erb
<div class="bg-container-full">

<div class="container main-card-index d-flex flex-column align-items-start justify-content-start card-content" style="margin-bottom: 100px; padding-bottom: 200px">
<img class="corner-img" src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678881148/corner_image_menoet.png">

<h1 class="w-full all-content">My Menus</h1>
<hr class="full">

<p class="pb-30">Choose the restaurant your menu is associated with, or add a new restaurant.</p>
 <p class ="btn-primary-cards mb-20" ><%= link_to 'Add a New Restaurant', new_user_restaurant_path %></p>

<% if @restaurants.any? %>
<nav class="menu w-full">
  <ol class="d-flex align-items-center justify-content-around w-full">
    <% @restaurants.each do |restaurant| %>
        <% if restaurant.user_id = current_user.id %>

    <li class="menu-item d-flex flex-column align-items-center w-half mt-0">
         <div class="menu-img mx-auto"> <%= image_tag("#{@images.sample}")%></div>
      <%= link_to restaurant.name, user_restaurant_path(current_user, restaurant) %><p class="triangle">></p>
      <ol class="sub-menu align-items-center justify-content-center">
        <% restaurant.menus.each do |menu|%>
        <li class="menu-item w-full mx-auto"><%= link_to menu.menu_name, edit_user_restaurant_menu_path(@user, restaurant, menu)%></li>
        <% end %>
      </ol>
</li>



<% end %>

  <% end %>


<% else %>
  <p>You haven't added any restaurants yet.</p>
<% end %>

</ol>
</nav>
</div>

</div>

</div>

</div>

app/views/restaurants/new.html.erb
<div class="bg-container-full">
  <div class="container main-card-index d-flex flex-column align-items-stretch card-content">
  <img class="corner-img" src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678881148/corner_image_menoet.png">
  <img class="sidebar-full" src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678891956/sidebar_cooking_lgruev.png">
    <div class="container p-20"; style="margin-bottom: 50px;">
      <h1 class="w-full all-content">New Restaurant</h1>
      <h4>Fill out your Restaurant information</h4>

      <%= form_with model: @restaurant, url: user_restaurants_path do |form| %>
        <% if @restaurant.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

            <ul>
              <% @restaurant.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field mb-10">
          <%= form.label :name %>
          <%= form.text_field :name %>
        </div>

        <div class="field mb-10">
          <%= form.label :cuisine %>
          <%= form.text_field :cuisine %>
        </div>

        <div class="field mb-10">
          <%= form.label :address %>
          <%= form.text_field :address %>
        </div>

        <div class="field mb-10">
          <%= form.label :phone_number %>
          <%= form.text_field :phone_number %>
        </div>

        <div class="field mb-10">
          <%= form.label :website %>
          <%= form.text_field :website %>
        </div>

        <div class="field mb-10">
          <%= form.label :email %>
          <%= form.text_field :email %>
        </div>
      <br>
        <div class="actions">
          <%= form.submit 'Next', class: "btn-primary-cards" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<body style="height: 100%">
<div class="bg-container-full">

  <div class="container main-card-index d-flex flex-column align-items-stretch card-content px-10">
  <img class="corner-img" src="https://res.cloudinary.com/dobohmdlf/image/upload/v1678881148/corner_image_menoet.png">

    <div class="d-flex justify-content-around mt-20 pt-20">
    <div class="d-flex flex-column">
      <div class="w-full my-0 mt-20" style="text-align:left"><h1 class="my-0">Menus for <strong><%= @restaurant.name %></strong></h1></div>


        <p class="mt-10"><strong>Cuisine: </strong><%= @restaurant.cuisine %></p>
        <p class="mt-10"><strong>Address: </strong><%= @restaurant.address %></p>
        <p class="mt-10"><strong>Phone Number:</strong> <%= @restaurant.phone_number %></p>
        <p class="mt-10"><strong>Website: </strong><%= @restaurant.website %></p>
        <p class="mt-10"><strong>Email:</strong> <%= @restaurant.email %></p>

    </div>
    <div>

          <% if policy(@restaurant).edit? %>

            <p class ="btn-secondary-cards my-20" ><%= link_to "Edit this restaurant", edit_user_restaurant_path(@restaurant) %><p>
          <%= button_to "Delete this Restaurant", {:controller => :restaurants,
                :action => 'destroy' }, class: "btn-secondary-cards", :method => :delete %>
          <% end %>
</div>
</div>

<div class="d-flex align-items-center justify-content-center card-content" style="text-align: center">
   <% @restaurant.menus.each do |menu| %>
   <div class="d-flex flex-column">
   <%= link_to edit_user_restaurant_menu_path(@user, @restaurant, menu) do %>
     <div class="menu-img mx-auto"> <%= image_tag("#{@images.sample}")%></div>
     <h4> <%= menu.menu_name %></h4>
     </div>
    <% end %>
    <% end %>


</div>
<div class="d-flex align-items-center justify-content-center card-content">
 <p class ="btn-primary-cards" > <%= link_to "Add a Menu", new_user_restaurant_menu_path(current_user, @restaurant) %></p>
</div>

<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
</div>
</div>
  </div>